name: Jeremiah Cox
favicon: null
layout_spectrum: 0.4389483192935586
typography_spectrum: 0.6935003574471921
title: Jeremiah Cox Dot Com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6785309368278831
  lightness: 0.2930636534001678
  saturation: 0.19367003091610968
  rhythmicContrast: 0.21703611384145916
purpose: []
