title: Jeremiah Cox Dot Com
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.546595
  lightness: 0.8387097
  brandStrength: 0.6785309368278831
  brandColors: []
  rhythmicContrast: 0.3673835
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Jeremiah Cox
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6935003574471921
layout_spectrum: 0.953405
